language: node_js
node_js:
  - "8"
  - "10"
os:
  - linux
  - osx
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy: ./scripts/build.sh
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: builds/*.zip
  skip_cleanup: true
  on:
    tags: true